name: Daily NFL Props

on:
  schedule:
    - cron: "0 13 * * *"   # 13:00 UTC = 9:00 AM America/Nassau
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy python-dateutil requests beautifulsoup4 lxml

      - name: Make scripts executable
        run: |
          chmod +x handsfree_runner.sh || true
          chmod +x handsfree_runner_plus.sh || true
          chmod +x ci_run.sh || true

      - name: Run daily props and push results
        run: |
          bash ci_run.sh